### ISSUE TITLE
Node JS

### ISSUE THREAD

**Issue by sproogen** [sproogen/itsgoingto.be#240]
Rewrite the backed in Node JS. Simple
### Todo
- [x] Rewrite APIs
  - [x] Get polls
  - [x] Create poll
  - [x] Get poll
  - [x] Delete poll
  - [x] Get responses
  - [x] Submit responses
  - [x] Login
  - [x] Get stats
- [x] Migrate socket server
- [x] Database migration
- [x] Production setup
- [x] API Tests
- [x] Remove PHP
- [x] Tidy project
  - [x] `Can't perform a React state update on an unmounted component.` when submitting passphrase on answer page
  - [x] Fix 'Multiple choice responses' checkbox
  - [x] Fix 'new poll' button style
  - [x] Update 'ask' route tests

#### Extras
- [x] Don't rebuild database on file change
- [x] Swagger
  - [x] Get polls
  - [x] Create poll
  - [x] Get poll
  - [x] Delete poll
  - [x] Get responses
  - [x] Submit responses
  - [x] Login
  - [x] Get stats
- [x] Update readme documentation

**Comment by sproogen** [comment]
https://github.com/sequelize/sequelize

**Comment by sproogen** [comment]
https://medium.com/codebase/structure-of-a-nodejs-api-project-cdecb46ef3f8

https://medium.com/the-andela-way/structuring-an-express-js-api-fc62efa038c5

**Comment by sproogen** [comment]
https://zellwk.com/blog/async-await-express/

**Comment by sproogen** [comment]
https://itnext.io/javascript-error-handling-from-express-js-to-react-810deb5e5e28

**Comment by sproogen** [comment]
app.use(morgan('combined'))
app.use(bodyParser.urlencoded({ extended: false }))

**Comment by sproogen** [comment]
https://expressjs.com/en/advanced/best-practice-performance.html

**Comment by sproogen** [comment]
https://learnwithparam.com/blog/basic-routing-in-react-router/
